import type { DefaultTheme } from 'vitepress'

/** Traditional Chinese navigation generated by scripts/convert-zh-tw.py. */
export const navTW = [
      { text: '首頁', link: '/zh-TW/' },
      {
        text: '開始學習',
        items: [
          {
            text: '學習入口',
            items: [
              { text: '從零開始操作', link: '/zh-TW/guide/start-here' },
              { text: '完整學習目錄', link: '/zh-TW/guide/' },
              { text: '從導論開始', link: '/zh-TW/guide/introduction' },
              { text: 'Pi 完整執行原理', link: '/zh-TW/guide/how-pi-works' }
            ]
          },
          {
            text: '完成課程',
            items: [
              { text: 'CASE 08 · 畢業專案', link: '/zh-TW/cases/graduation-project' }
            ]
          }
        ]
      },
      {
        text: '動手實踐',
        items: [
          {
            text: '案例與擴充',
            items: [
              { text: '實作案例庫', link: '/zh-TW/cases/' },
              { text: '外掛程式推薦與選擇', link: '/zh-TW/plugins/' },
              { text: '技能、擴充功能與套件', link: '/zh-TW/guide/skills-extensions-packages' }
            ]
          },
          {
            text: '管理與安全',
            items: [
              { text: '安裝後生命週期管理', link: '/zh-TW/guide/lifecycle-management' },
              { text: '權限、隔離與驗收', link: '/zh-TW/guide/safety' }
            ]
          }
        ]
      },
      {
        text: '查問題',
        items: [
          {
            text: '快速定位',
            items: [
              { text: '參考手冊首頁', link: '/zh-TW/reference/' },
              { text: '常見問題 FAQ', link: '/zh-TW/reference/faq' },
              { text: '故障排查手冊', link: '/zh-TW/reference/troubleshooting' },
              { text: 'AI 與 Agent 熱詞', link: '/zh-TW/reference/glossary' }
            ]
          }
        ]
      },
      {
        text: '延伸資料',
        items: [
          {
            text: '文章與檔案',
            items: [
              { text: 'Earendil 授權譯文', link: '/zh-TW/translations/' },
              { text: '小墨札記', link: '/zh-TW/journey/' },
              { text: '98 條推文檔案', link: '/zh-TW/tweets/' }
            ]
          },
          {
            text: '專案',
            items: [
              { text: 'GitHub 倉庫', link: 'https://github.com/xiaomoBoy/pi-bluebook' }
            ]
          }
        ]
      },
      { text: '聯絡合作', link: 'https://xiaomovps.com/' }
    ] satisfies DefaultTheme.NavItem[]

/** Traditional Chinese sidebars generated from navigation.mts. */
export const sidebarTW = {
      '/zh-TW/guide/': [
        {
          text: '藍皮書',
          collapsed: true,
          items: [
            { text: '完整學習目錄', link: '/zh-TW/guide/' },
            { text: '從零開始操作', link: '/zh-TW/guide/start-here' },
            { text: '導論 · 為什麼讀這本書', link: '/zh-TW/guide/introduction' },
            { text: '十條仍然成立的判斷', link: '/zh-TW/guide/lasting-principles' },
            { text: '凡例與本版說明', link: '/zh-TW/guide/edition-2026' },
            { text: '序章 · Pi 作者 Mario Zechner', link: '/zh-TW/guide/mario-zechner' }
          ]
        },
        {
          text: '模組一 · 安裝與基礎設定',
          collapsed: true,
          items: [
            { text: '1. 安裝前檢查', link: '/zh-TW/guide/before-install' },
            { text: '2. 安裝並啟動 Pi', link: '/zh-TW/guide/install-pi' },
            { text: 'Windows 中文安裝路徑', link: '/zh-TW/guide/windows-setup' },
            { text: '3. 登入與模型設定', link: '/zh-TW/guide/connect-model' },
            { text: '4. 從練習目錄開始', link: '/zh-TW/guide/ready-to-work' },
            { text: '維護 · 更新、退出與解除安裝', link: '/zh-TW/guide/lifecycle-management' }
          ]
        },
        {
          text: '模組二 · 完成真實任務',
          collapsed: true,
          items: [
            { text: '5. 第一次任務', link: '/zh-TW/guide/first-task' },
            { text: '6. 檔案與工作目錄', link: '/zh-TW/guide/files-and-context' },
            { text: '7. 工作階段的儲存與續寫', link: '/zh-TW/guide/sessions' }
          ]
        },
        {
          text: '模組三 · 長任務與上下文',
          collapsed: true,
          items: [
            { text: '8. 上下文與壓縮', link: '/zh-TW/guide/context-and-compaction' },
            { text: '9. 提示快取入門', link: '/zh-TW/guide/prompt-caching' }
          ]
        },
        {
          text: '模組四 · 擴充自己的 Pi',
          collapsed: true,
          items: [
            { text: '10. 技能、擴充功能與套件', link: '/zh-TW/guide/skills-extensions-packages' },
            { text: '11. 擴充功能的需求與驗收', link: '/zh-TW/guide/first-extension' },
            { text: '12. 子代理如何分工', link: '/zh-TW/guide/subagents' }
          ]
        },
        {
          text: '原理串聯',
          collapsed: true,
          items: [
            { text: '從 Prompt 到 Agent Loop', link: '/zh-TW/guide/how-pi-works' }
          ]
        },
        {
          text: '模組五 · 穩定工作流',
          collapsed: true,
          items: [
            { text: '13. 長時間任務與 VPS', link: '/zh-TW/guide/vps-and-long-running' },
            { text: '14. 權限、隔離與驗收', link: '/zh-TW/guide/safety' }
          ]
        },
        {
          text: '結課與查錯',
          collapsed: true,
          items: [
            { text: 'CASE 08 · 畢業專案', link: '/zh-TW/cases/graduation-project' },
            { text: 'Pi 故障排查手冊', link: '/zh-TW/reference/troubleshooting' }
          ]
        }
      ],
      '/zh-TW/cases/': [
        {
          text: '開始實踐',
          collapsed: true,
          items: [
            { text: '案例庫與使用方法', link: '/zh-TW/cases/' },
            { text: '藍皮書完整目錄', link: '/zh-TW/guide/' }
          ]
        },
        {
          text: '單項練習 · CASE 01–07',
          collapsed: true,
          items: [
            { text: 'CASE 01 · 會議記錄行動清單', link: '/zh-TW/cases/meeting-notes' },
            { text: 'CASE 02 · 壓縮前後對照', link: '/zh-TW/cases/compaction-before-after' },
            { text: 'CASE 03 · 第一個技能', link: '/zh-TW/cases/first-skill' },
            { text: 'CASE 04 · 最小擴充功能', link: '/zh-TW/cases/first-extension' },
            { text: 'CASE 05 · 兩路獨立審閱', link: '/zh-TW/cases/independent-review' },
            { text: 'CASE 06 · 從檢查點恢復', link: '/zh-TW/cases/checkpoint-recovery' },
            { text: 'CASE 07 · 任務前安全審閱', link: '/zh-TW/cases/safe-review' }
          ]
        },
        {
          text: '遷移練習',
          collapsed: true,
          items: [
            { text: '從資料到可核對的草稿', link: '/zh-TW/cases/content-workflow' },
            { text: '修復一個小程式', link: '/zh-TW/cases/code-repair' }
          ]
        },
        {
          text: '綜合結課',
          collapsed: true,
          items: [
            { text: 'CASE 08 · Pi 藍皮書畢業專案', link: '/zh-TW/cases/graduation-project' }
          ]
        },
        {
          text: '遇到問題',
          collapsed: true,
          items: [{ text: 'Pi 故障排查手冊', link: '/zh-TW/reference/troubleshooting' }]
        }
      ],
      '/zh-TW/plugins/': [
        {
          text: '選擇與理解',
          collapsed: true,
          items: [
            { text: '推薦總覽與選擇方法', link: '/zh-TW/plugins/' },
            { text: '技能、擴充功能與套件', link: '/zh-TW/guide/skills-extensions-packages' }
          ]
        },
        {
          text: '動手練習',
          collapsed: true,
          items: [
            { text: 'CASE 03 · 第一個技能', link: '/zh-TW/cases/first-skill' },
            { text: 'CASE 04 · 最小擴充功能', link: '/zh-TW/cases/first-extension' }
          ]
        },
        {
          text: '管理與排查',
          collapsed: true,
          items: [
            { text: '安裝後生命週期管理', link: '/zh-TW/guide/lifecycle-management' },
            { text: '擴充功能載入失敗', link: '/zh-TW/reference/troubleshooting#extension-failed' },
            { text: '外掛程式互相衝突', link: '/zh-TW/reference/troubleshooting#resource-conflict' },
            { text: '權限、隔離與驗收', link: '/zh-TW/guide/safety' }
          ]
        },
        {
          text: '原始記錄',
          collapsed: true,
          items: [{ text: '技能與擴充功能推文', link: '/zh-TW/tweets/04-skills-extensions' }]
        }
      ],
      '/zh-TW/reference/': [
        {
          text: '快速查問題',
          collapsed: true,
          items: [
            { text: '主題索引', link: '/zh-TW/reference/' },
            { text: '常見問題 FAQ', link: '/zh-TW/reference/faq' },
            { text: 'Pi 故障排查手冊', link: '/zh-TW/reference/troubleshooting' },
            { text: 'AI 與 Agent 熱詞', link: '/zh-TW/reference/glossary' }
          ]
        },
        {
          text: '理解執行機制',
          collapsed: true,
          items: [
            { text: '從 Prompt 到 Agent Loop', link: '/zh-TW/guide/how-pi-works' },
            { text: '檔案與工作目錄', link: '/zh-TW/guide/files-and-context' },
            { text: '工作階段與續寫', link: '/zh-TW/guide/sessions' },
            { text: '上下文與壓縮', link: '/zh-TW/guide/context-and-compaction' },
            { text: '提示快取', link: '/zh-TW/guide/prompt-caching' }
          ]
        },
        {
          text: '能力與邊界',
          collapsed: true,
          items: [
            { text: '技能、擴充功能與套件', link: '/zh-TW/guide/skills-extensions-packages' },
            { text: '外掛程式推薦與選擇', link: '/zh-TW/plugins/' },
            { text: '子代理', link: '/zh-TW/guide/subagents' },
            { text: '權限、隔離與驗收', link: '/zh-TW/guide/safety' }
          ]
        },
        {
          text: '繼續學習',
          collapsed: true,
          items: [
            { text: '藍皮書完整目錄', link: '/zh-TW/guide/' },
            { text: '8 個實作案例', link: '/zh-TW/cases/' }
          ]
        }
      ],
      '/zh-TW/translations/': [
        {
          text: '譯文目錄',
          collapsed: true,
          items: [
            { text: '十一篇授權譯文總覽', link: '/zh-TW/translations/' }
          ]
        },
        {
          text: '工作階段與上下文',
          collapsed: true,
          items: [
            { text: '無法隨身帶走的工作階段', link: '/zh-TW/translations/session-portability' },
            { text: 'Pi 中的壓縮機制', link: '/zh-TW/translations/compaction-in-pi' },
            { text: 'Agent 中的提示快取', link: '/zh-TW/translations/prompt-caching' }
          ]
        },
        {
          text: '代理框架與 Pi',
          collapsed: true,
          items: [
            { text: '什麼是代理框架？', link: '/zh-TW/translations/what-is-a-harness' },
            { text: '這個代理框架屬於我', link: '/zh-TW/translations/mine-agent-harness' },
            { text: 'Pi：極簡而高效', link: '/zh-TW/translations/pi-minimal-performant' }
          ]
        },
        {
          text: '公告與長期思考',
          collapsed: true,
          items: [
            { text: 'Pi 與 Lefos 正式釋出', link: '/zh-TW/translations/announcing-pi-and-lefos' },
            { text: '關於今日公告的思考', link: '/zh-TW/translations/announcement-reflection' },
            { text: '制高點', link: '/zh-TW/translations/the-high-ground' },
            { text: '邀請你開啟一場通訊', link: '/zh-TW/translations/invitation' }
          ]
        },
        {
          text: '程式碼品質與評估',
          collapsed: true,
          items: [
            { text: '衡量程式碼的粗糙程度', link: '/zh-TW/translations/measuring-code-sloppiness' }
          ]
        },
        {
          text: '回到藍皮書',
          collapsed: true,
          items: [
            { text: '從 Prompt 到 Agent Loop', link: '/zh-TW/guide/how-pi-works' },
            { text: '參考手冊主題索引', link: '/zh-TW/reference/' }
          ]
        }
      ],
      '/zh-TW/journey/': [
        {
          text: '小墨札記',
          collapsed: true,
          items: [
            { text: '寫在藍皮書之外', link: '/zh-TW/journey/' },
            { text: '98 條推文檔案', link: '/zh-TW/tweets/' }
          ]
        },
        {
          text: '學習階段',
          collapsed: true,
          items: [
            { text: '1. 從好奇開始認識 Pi', link: '/zh-TW/tweets/01-meet-pi' },
            { text: '2. 先把第一個任務做完', link: '/zh-TW/tweets/02-first-tasks' },
            { text: '3. 理解工作階段與上下文', link: '/zh-TW/tweets/03-sessions-context' },
            { text: '4. 技能與擴充功能', link: '/zh-TW/tweets/04-skills-extensions' },
            { text: '5. 讓子代理學會分工', link: '/zh-TW/tweets/05-subagents-research' },
            { text: '6. 把 Pi 變成長期工作流', link: '/zh-TW/tweets/06-long-running' }
          ]
        },
        {
          text: '回到當前結論',
          collapsed: true,
          items: [
            { text: '十條仍然成立的判斷', link: '/zh-TW/guide/lasting-principles' },
            { text: '藍皮書完整目錄', link: '/zh-TW/guide/' }
          ]
        }
      ],
      '/zh-TW/tweets/': [
        {
          text: '小墨札記',
          collapsed: true,
          items: [
            { text: '寫在藍皮書之外', link: '/zh-TW/journey/' },
            { text: '98 條推文檔案', link: '/zh-TW/tweets/' }
          ]
        },
        {
          text: '學習階段',
          collapsed: true,
          items: [
            { text: '1. 從好奇開始認識 Pi', link: '/zh-TW/tweets/01-meet-pi' },
            { text: '2. 先把第一個任務做完', link: '/zh-TW/tweets/02-first-tasks' },
            { text: '3. 理解工作階段與上下文', link: '/zh-TW/tweets/03-sessions-context' },
            { text: '4. 技能與擴充功能', link: '/zh-TW/tweets/04-skills-extensions' },
            { text: '5. 讓子代理學會分工', link: '/zh-TW/tweets/05-subagents-research' },
            { text: '6. 把 Pi 變成長期工作流', link: '/zh-TW/tweets/06-long-running' }
          ]
        },
        {
          text: '回到當前結論',
          collapsed: true,
          items: [
            { text: '十條仍然成立的判斷', link: '/zh-TW/guide/lasting-principles' },
            { text: '藍皮書完整目錄', link: '/zh-TW/guide/' }
          ]
        }
      ]
    } satisfies DefaultTheme.Sidebar
